#!/bin/bash
USER=orbiter

/usr/sbin/groupadd gpio
/usr/sbin/useradd ${USER} -r --gid gpio --home-dir /opt/orbiter -M
/bin/chown -R ${USER} /etc/orbiter
/bin/mkdir /opt/orbiter/log
/bin/chown ${USER} /opt/orbiter/log
/bin/mkdir /opt/orbiter/var
/bin/chown ${USER} /opt/orbiter/var
/bin/mkdir /var/log/orbiter
/bin/chown ${USER} /var/log/orbiter
systemctl daemon-reload
